#!/bin/sh
name=$1
type=$2
container=$3
if [ "$4" = "" ]; then
	path=$name
else
	path=`echo "$4" | sed -e "s:[^/]$:&/:"`$name
fi
if [ "$5" != "" ]; then
	heap=$5
fi

lower=`echo $container | tr "[:upper:]" "[:lower:]"`
upper=`echo $container | tr "[:lower:]" "[:upper:]"`

hdr="\
#include <cstl/${lower}.h>
#undef CSTL_VECTOR_MAGIC
#define CSTL_VECTOR_MAGIC(x) CSTL_VECTOR_MAGIC(x)
#undef CSTL_RING_MAGIC
#define CSTL_RING_MAGIC(x) CSTL_RING_MAGIC(x)
#undef CSTL_DEQUE_MAGIC
#define CSTL_DEQUE_MAGIC(x) CSTL_DEQUE_MAGIC(x)
#undef CSTL_LIST_MAGIC
#define CSTL_LIST_MAGIC(x) CSTL_LIST_MAGIC(x)
#undef CSTL_STRING_MAGIC
#define CSTL_STRING_MAGIC(x) CSTL_STRING_MAGIC(x)
CSTL_${upper}_INTERFACE($name, $type)"

src="\
#include <cstl/${lower}.h>
#include <cstl/algorithm.h>
#undef assert
#define assert(x) assert(x)
#undef CSTL_VECTOR_MAGIC
#define CSTL_VECTOR_MAGIC(x) CSTL_VECTOR_MAGIC(x)
#undef CSTL_RING_MAGIC
#define CSTL_RING_MAGIC(x) CSTL_RING_MAGIC(x)
#undef CSTL_DEQUE_MAGIC
#define CSTL_DEQUE_MAGIC(x) CSTL_DEQUE_MAGIC(x)
#undef CSTL_LIST_MAGIC
#define CSTL_LIST_MAGIC(x) CSTL_LIST_MAGIC(x)
#undef CSTL_STRING_MAGIC
#define CSTL_STRING_MAGIC(x) CSTL_STRING_MAGIC(x)
CSTL_${upper}_IMPLEMENT($name, $type)"

rev=`grep '$Id' "../cstl/${lower}.h"`
vectorrev=`grep '$Id' "../cstl/vector.h"`
ringrev=`grep '$Id' "../cstl/ring.h"`
algorev=`grep '$Id' "../cstl/algorithm.h"`

# ヘッダファイル生成
included=`echo "$name""_H_INCLUDED" | tr "[:lower:]" "[:upper:]"`
echo -e "/* generated by $0" > "$path"".h"
echo -e "${rev}" >> "$path"".h"
if [ $lower = "deque" ]; then
	echo -e "${vectorrev}" >> "$path"".h"
	echo -e "${ringrev}" >> "$path"".h"
elif [ $lower = "string" ]; then
	echo -e "${vectorrev}" >> "$path"".h"
fi
if [ $lower != "list" ]; then
	echo -e "${algorev}" >> "$path"".h"
fi
echo -e " */" >> "$path"".h"
echo -e "#ifndef $included\n#define $included\n" >> "$path"".h"
echo -e "#include <stddef.h>\n" >> "$path"".h"
if [ $lower = "ring" ]; then
echo -e "\
#ifndef NDEBUG
#define CSTL_${upper}_MAGIC(x) x
#else
#define CSTL_${upper}_MAGIC(x)
#endif\n" >> "$path"".h"
fi
echo "$hdr" | cpp -I.. | grep "$name" | indent -kr -ut -ts4 \
| sed -e "s/$name \* /$name */g" >> "$path"".h"
echo -e "\n#endif /* $included */" >> "$path"".h"

# ソースファイル生成
echo -e "/* generated by $0" > "$path"".c"
echo -e "${rev}" >> "$path"".c"
if [ $lower = "deque" ]; then
	echo -e "${vectorrev}" >> "$path"".c"
	echo -e "${ringrev}" >> "$path"".c"
elif [ $lower = "string" ]; then
	echo -e "${vectorrev}" >> "$path"".c"
fi
if [ $lower != "list" ]; then
	echo -e "${algorev}" >> "$path"".c"
fi
echo -e " */" >> "$path"".c"
echo -e "#include <stdlib.h>" >> "$path"".c"
echo -e "#include <assert.h>" >> "$path"".c"
echo -e "#include \"$name.h\"\n" >> "$path"".c"
if [ $lower != "ring" ]; then
if [ $lower = "deque" ]; then
echo -e "\
#ifndef NDEBUG
#define CSTL_${upper}_MAGIC(x) x
#define CSTL_VECTOR_MAGIC(x) x
#define CSTL_RING_MAGIC(x) x
#else
#define CSTL_${upper}_MAGIC(x)
#define CSTL_VECTOR_MAGIC(x)
#define CSTL_RING_MAGIC(x)
#endif\n" >> "$path"".c"
elif [ $lower = "string" ]; then
echo -e "\
#ifndef NDEBUG
#define CSTL_${upper}_MAGIC(x) x
#define CSTL_VECTOR_MAGIC(x) x
#else
#define CSTL_${upper}_MAGIC(x)
#define CSTL_VECTOR_MAGIC(x)
#endif\n" >> "$path"".c"
else
echo -e "\
#ifndef NDEBUG
#define CSTL_${upper}_MAGIC(x) x
#else
#define CSTL_${upper}_MAGIC(x)
#endif\n" >> "$path"".c"
fi
fi
if [ "$heap" != "" ]; then
echo -e "\
#include \"heap.h\"
extern Heap $heap;
#define malloc(s)      Heap_alloc(&$heap, s)
#define realloc(p, s)  Heap_realloc(&$heap, p, s)
#define free(p)        Heap_free(&$heap, p)
" >> "$path"".c"
fi
echo "$src" | cpp -I.. | grep "$name" | indent -kr -ut -ts4 \
| sed -e "s/$name \* /$name */g" | sed -e "s/^} /}\n\n/" >> "$path"".c"

gcc -Wall "$path"".c" -c

